### ISSUE TITLE
如何修改成运行后不退出？

### ISSUE THREAD

**Issue by vshen009** [SuperNG6/docker-subfinder#1]
大佬你好，我在测试用你的 docker 版 subfinder，是否可以改成 启动用 定时扫描目录 ，而不是 启动扫描完成后退出？ 我是在nas上跑docker。如果改成hourly 扫码会变的非常方便。感谢你的修改！

**Comment by SuperNG6** [comment]
下次增加加上，我还不太懂 S6的定时任务怎么写

**Comment by SuperNG6** [comment]
新版已添加
